"""Minimal typed placeholders for the future MCP integration layer.

These exports are pre-stable design artifacts for a future read-only MCP
surface. They are not a declared stable public API yet.
"""

from repo_semantic_memory.mcp.handlers import (
    handle_build_context_pack,
    handle_explain_entity,
    handle_export_ai_memory,
    handle_get_git_summary,
    handle_query_graph,
    handle_search_symbols,
    handle_validate_patch_context,
)
from repo_semantic_memory.mcp.runtime import (
    DEFERRED_TOOL_NAMES,
    LEGACY_TOOL_NAMES,
    PHASE1_TOOL_NAMES,
    PUBLIC_TOOL_NAMES,
    STORE_ONLY_TOOL_NAMES,
    STORE_PUBLIC_TOOL_NAMES,
    STORE_TOOL_NAMES,
    ActiveIndex,
    SessionConfig,
    StoreSessionState,
    ToolDescriptor,
    ToolInvocationError,
    build_store_tool_registry,
    build_tool_registry,
    invoke_tool,
    validate_session,
)
from repo_semantic_memory.mcp.server import run_serve, run_serve_store, serve_stdio
from repo_semantic_memory.mcp.tools import (
    BudgetEnvelope,
    BuildContextPackRequest,
    BuildContextPackResponse,
    Citation,
    ExplainEntityRequest,
    ExplainEntityResponse,
    ExportAiMemoryRequest,
    ExportAiMemoryResponse,
    GetGitSummaryRequest,
    GetGitSummaryResponse,
    McpToolName,
    QueryGraphRequest,
    QueryGraphResponse,
    SearchSymbolsRequest,
    SearchSymbolsResponse,
    ToolContract,
    Uncertainty,
    ValidatePatchContextRequest,
    ValidatePatchContextResponse,
    get_mcp_tool_contracts,
)

__all__ = [
    "ActiveIndex",
    "BudgetEnvelope",
    "BuildContextPackRequest",
    "BuildContextPackResponse",
    "Citation",
    "DEFERRED_TOOL_NAMES",
    "ExplainEntityRequest",
    "ExplainEntityResponse",
    "ExportAiMemoryRequest",
    "ExportAiMemoryResponse",
    "GetGitSummaryRequest",
    "GetGitSummaryResponse",
    "LEGACY_TOOL_NAMES",
    "McpToolName",
    "PHASE1_TOOL_NAMES",
    "PUBLIC_TOOL_NAMES",
    "STORE_ONLY_TOOL_NAMES",
    "STORE_PUBLIC_TOOL_NAMES",
    "STORE_TOOL_NAMES",
    "QueryGraphRequest",
    "QueryGraphResponse",
    "SearchSymbolsRequest",
    "SearchSymbolsResponse",
    "SessionConfig",
    "StoreSessionState",
    "ToolContract",
    "ToolDescriptor",
    "ToolInvocationError",
    "Uncertainty",
    "ValidatePatchContextRequest",
    "ValidatePatchContextResponse",
    "build_store_tool_registry",
    "build_tool_registry",
    "handle_build_context_pack",
    "handle_explain_entity",
    "handle_export_ai_memory",
    "handle_get_git_summary",
    "handle_query_graph",
    "handle_search_symbols",
    "handle_validate_patch_context",
    "get_mcp_tool_contracts",
    "invoke_tool",
    "run_serve",
    "run_serve_store",
    "serve_stdio",
    "validate_session",
]
