"""Export semantic memory as portable `.ai/` directory for agent consumption.

Generated files are compact, deterministic (except timestamps), and carry
provenance metadata. Source of truth always remains code/docs/tests/git.

License: Apache-2.0
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from repo_semantic_memory.context.repo_map import build_repo_map_markdown
from repo_semantic_memory.memory.ecs_components import infer_semantic_components
from repo_semantic_memory.model import Entity, Relation, SemanticComponent
from repo_semantic_memory.version import CONTEXT_PACK_VERSION, PACKAGE_VERSION, SCHEMA_VERSION

# Budget for embedded repo map in .ai/ export (compact, not full budget)
_REPO_MAP_BUDGET = 8000

_README_TEMPLATE = """\
# .ai/ — Agent Semantic Memory

> **WARNING**: These files are generated artifacts. They may be stale.
> Source of truth is always the code, docs, tests, and git history.
> Regenerate with: `rsm export-ai --db .rsm/index.sqlite --out .ai`

## Purpose

This directory contains compact semantic memory files for coding agents.
It is NOT a human documentation replacement.

## Files

| File | Description |
|---|---|
| `INDEX.yaml` | Versions, source DB path, generation timestamp, entity/relation counts |
| `repo_map.md` | Compact structural map of the repository |
| `symbols.yaml` | Stable entity IDs, kinds, names, and source locations |
| `relations.yaml` | Directed structural relations between entities |
| `components.yaml` | Inferred ECS-style semantic component labels (if present) |
| `invariants.yaml` | Inferred invariant entities (if present) |
| `context_policy.md` | How to use these files in agent context windows |

## Git behaviour

Projects may choose to commit generated `.ai/` outputs.
If committed, treat them as compiled semantic artifacts (like generated protobufs).
The `.rsm/` index (SQLite) must NOT be committed — it is local only.

## License

Generated by `repo-semantic-memory` — Apache-2.0
Source: https://github.com/apajon/repo-semantic-memory
"""

_CONTEXT_POLICY_TEMPLATE = """\
# Context Policy

This file describes how coding agents should use `.ai/` semantic memory files.

## Source of truth

Code, docs, tests, and git history are always authoritative.
These files are derived snapshots and may be stale.

## Recommended usage

1. Load `INDEX.yaml` to confirm generation timestamp and versions.
2. Load `repo_map.md` for structural orientation.
3. Load `symbols.yaml` to resolve entity IDs and source locations.
4. Load `relations.yaml` to understand structural dependencies.
5. Load `components.yaml` to identify semantic roles (if present).
6. Load `invariants.yaml` to understand declared invariants (if present).

## Budget guidance

Prefer loading only files relevant to the current task.
`repo_map.md` provides the broadest structural context at lowest token cost.
`symbols.yaml` and `relations.yaml` together provide full graph context.

## Compression profiles

`rsm repo-map` and `rsm pack` support deterministic profiles:

- `agent_brief`: smallest output, suppresses unresolved imports and low-signal detail.
- `agent_standard`: default balanced profile for most coding tasks.
- `agent_debug`: keeps ranking breakdown and compact score reasons for diagnostics.
- `human_review`: balanced for human PR/design review workflows.
- `ci_summary`: compact CI-oriented output with strict noise suppression.
- `full`: maximum verbosity while still avoiding source body dumps.

Profile controls include:

- max imports per module
- max components per entity
- unresolved import inclusion
- ranking breakdown inclusion
- low-confidence inferred component inclusion
- relation verbosity
- citation verbosity
- max related symbols
- max uncertainties
- compact score reason inclusion

Preservation rules always favor:

- direct task matches
- source citations
- explicit public exports
- high-confidence structural context
- selected implementation symbols

## Staleness

Check `INDEX.yaml` → `generated_at` field against recent git commits.
Regenerate when indexing adds new symbols or structural changes occur.

## License

Apache-2.0 — generated by `repo-semantic-memory`
"""


@dataclass(frozen=True)
class ExportResult:
    """Summary of a completed `.ai/` export operation."""

    output_dir: Path
    files_written: tuple[str, ...]
    files_skipped: tuple[str, ...]
    entity_count: int
    relation_count: int
    component_count: int
    invariant_count: int


@dataclass
class AiDirectoryExporter:
    """Exports indexed semantic data as a portable `.ai/` directory."""

    db_path: Path
    output_dir: Path
    entities: list[Entity] = field(default_factory=list)
    relations: list[Relation] = field(default_factory=list)
    metadata: dict[str, str] = field(default_factory=dict)
    generated_at: str = ""

    def export(self, *, force: bool = False) -> ExportResult:
        """Write all `.ai/` files, respecting overwrite policy.

        Args:
            force: When True, overwrite existing generated files.
                   When False, skip files that already exist.

        Returns:
            ExportResult summarising what was written and skipped.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)

        components = infer_semantic_components(entities=self.entities, relations=self.relations)
        invariant_entities = [e for e in self.entities if e.kind == "invariant"]

        files_written: list[str] = []
        files_skipped: list[str] = []

        def _write(name: str, content: str) -> None:
            target = self.output_dir / name
            if target.exists() and not force:
                files_skipped.append(name)
                return
            target.write_text(content, encoding="utf-8")
            files_written.append(name)

        _write("README.md", _README_TEMPLATE)
        _write("context_policy.md", _CONTEXT_POLICY_TEMPLATE)
        _write("INDEX.yaml", self._build_index_yaml(components, invariant_entities))
        _write("repo_map.md", self._build_repo_map())
        _write("symbols.yaml", self._build_symbols_yaml())
        _write("relations.yaml", self._build_relations_yaml())

        if components:
            _write("components.yaml", self._build_components_yaml(components))
        if invariant_entities:
            _write("invariants.yaml", self._build_invariants_yaml(invariant_entities))

        return ExportResult(
            output_dir=self.output_dir,
            files_written=tuple(sorted(files_written)),
            files_skipped=tuple(sorted(files_skipped)),
            entity_count=len(self.entities),
            relation_count=len(self.relations),
            component_count=len(components),
            invariant_count=len(invariant_entities),
        )

    # ------------------------------------------------------------------
    # File content builders
    # ------------------------------------------------------------------

    def _build_index_yaml(
        self,
        components: Sequence[SemanticComponent],
        invariant_entities: Sequence[Entity],
    ) -> str:
        lines = [
            "# .ai/INDEX.yaml — semantic memory index manifest",
            "# WARNING: Generated file. Regenerate with: rsm export-ai",
            "# Apache-2.0 — repo-semantic-memory",
            "",
            f"generated_at: {self.generated_at!r}",
            f"source_db: {str(self.db_path)!r}",
            "",
            "versions:",
            f"  package_version: {PACKAGE_VERSION!r}",
            f"  schema_version: {SCHEMA_VERSION!r}",
            f"  context_pack_version: {CONTEXT_PACK_VERSION!r}",
            "",
            "counts:",
            f"  entities: {len(self.entities)}",
            f"  relations: {len(self.relations)}",
            f"  components: {len(components)}",
            f"  invariants: {len(invariant_entities)}",
        ]
        if self.metadata:
            lines += ["", "extraction_metadata:"]
            for key in sorted(self.metadata.keys()):
                value = self.metadata[key]
                lines.append(f"  {key}: {value!r}")
        lines.append("")
        return "\n".join(lines)

    def _build_repo_map(self) -> str:
        return build_repo_map_markdown(self.entities, self.relations, budget_chars=_REPO_MAP_BUDGET)

    def _build_symbols_yaml(self) -> str:
        lines = [
            "# .ai/symbols.yaml — entity symbol index",
            "# WARNING: Generated file. Regenerate with: rsm export-ai",
            "# Apache-2.0 — repo-semantic-memory",
            "",
            "symbols:",
        ]
        for entity in sorted(self.entities, key=lambda e: e.id.value):
            path = entity.source_range.path
            citation = f"{path}:{entity.source_range.start_line}"
            lines.append(f"  - id: {entity.id.value!r}")
            lines.append(f"    kind: {entity.kind!r}")
            lines.append(f"    name: {entity.name!r}")
            lines.append(f"    qualified_name: {entity.qualified_name!r}")
            lines.append(f"    source: {citation!r}")
        lines.append("")
        return "\n".join(lines)

    def _build_relations_yaml(self) -> str:
        lines = [
            "# .ai/relations.yaml — structural relation graph",
            "# WARNING: Generated file. Regenerate with: rsm export-ai",
            "# Apache-2.0 — repo-semantic-memory",
            "",
            "relations:",
        ]
        ordered = sorted(
            self.relations,
            key=lambda r: (r.kind, r.source_entity_id.value, r.target_entity_id.value),
        )
        for relation in ordered:
            lines.append(f"  - kind: {relation.kind!r}")
            lines.append(f"    source: {relation.source_entity_id.value!r}")
            lines.append(f"    target: {relation.target_entity_id.value!r}")
            if relation.evidence is not None:
                evidence_dict = relation.evidence.to_dict()
                citation = _evidence_citation(evidence_dict)
                if citation:
                    lines.append(f"    citation: {citation!r}")
        lines.append("")
        return "\n".join(lines)

    def _build_components_yaml(self, components: Sequence[SemanticComponent]) -> str:
        lines = [
            "# .ai/components.yaml — inferred ECS semantic component labels",
            "# WARNING: Generated file. Regenerate with: rsm export-ai",
            "# Apache-2.0 — repo-semantic-memory",
            "",
            "components:",
        ]
        ordered = sorted(
            components,
            key=lambda c: (c.component_type, c.entity_id.value),
        )
        for component in ordered:
            lines.append(f"  - component_type: {component.component_type!r}")
            lines.append(f"    entity_id: {component.entity_id.value!r}")
            lines.append(f"    status: {component.status!r}")
            lines.append(f"    confidence: {component.confidence:.2f}")
            if component.inference_note:
                lines.append(f"    note: {component.inference_note!r}")
        lines.append("")
        return "\n".join(lines)

    def _build_invariants_yaml(self, invariant_entities: Sequence[Entity]) -> str:
        lines = [
            "# .ai/invariants.yaml — invariant entities",
            "# WARNING: Generated file. Regenerate with: rsm export-ai",
            "# Apache-2.0 — repo-semantic-memory",
            "",
            "invariants:",
        ]
        for entity in sorted(invariant_entities, key=lambda e: e.id.value):
            path = entity.source_range.path
            citation = f"{path}:{entity.source_range.start_line}"
            lines.append(f"  - id: {entity.id.value!r}")
            lines.append(f"    name: {entity.name!r}")
            lines.append(f"    qualified_name: {entity.qualified_name!r}")
            lines.append(f"    source: {citation!r}")
        lines.append("")
        return "\n".join(lines)


def _evidence_citation(evidence_dict: dict[str, Any]) -> str | None:
    """Extract a compact citation string from an evidence dictionary."""
    source = evidence_dict.get("source_range")
    if not source:
        return None
    if isinstance(source, dict):
        path = source.get("path")
        line = source.get("start_line")
        if path:
            return f"{path}:{line}" if line is not None else str(path)
    return None
